### ISSUE TITLE
Clean up email template for giving

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#192]
@samclaridge I'll get you a login to beta-rock so you can edit this template directly. We should probably chat with @jonhorton about copy for this too.

**Comment by jonhorton** [comment]
I was just typing out a bug/todo for this. Creepy.

On Wednesday, February 24, 2016, James Baxley <notifications@github.com>
wrote:

> @samclaridge <https://github.com/samclaridge> I'll get you a login to
> beta-rock so you can edit this template directly. We should probably chat
> with @jonhorton <https://github.com/jonhorton> about copy for this too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NewSpring/Apollos/issues/192>.
>


-- 
Jon Horton
Central Web Director
NewSpring Church
www.newspring.cc
Office: 864.965.9518
Cell: 919.218.6655

**Comment by jbaxleyiii** [comment]
@jonhorton haha yesss!

**Comment by jbaxleyiii** [comment]
@jonhorton thoughts on when we will have copy for this? Are you writing it, do I need to have Amy write it?

**Comment by jonhorton** [comment]
@jbaxleyiii @samclaridge  Let's use the existing give copy we have (I've include a slightly modified version below), and we'll follow up with Amy after launch for any revisions. Place holders are surrounded with [ ] below. Also, the confirmation section should keep the same styles you already have in the template!

**Begin Copy**
Thank you for your generous gift of [$Amount] to NewSpring Church from your account ending in [Last 4 Digits]. Because you gave, we'll be able to reach more people far from God and teach them to follow Jesus step by step. Below is the confirmation number and details of your gift.

Confirmation Number: [XXXXXXX]
General Fund	[$XX.XX]
Total:	[$XX.XX}

[Scheduling your giving](https://my.newspring.cc/give/recurring) or viewing your [giving history](https://my.newspring.cc/give/history) is easy! Simply [sign in](https://my.newspring.cc/profile) or create a [NewSpring Profile](https://my.newspring.cc/profile).

If you have any questions please call our Finance Team at 864-965-9990 or e-mail us at finance@newspring.cc and we will be happy to assist you!
**End Copy**

We probably need to create a separate footer for the template used for this email. ([Screenshot](https://www.dropbox.com/s/d84vrlxfopb4ch8/Screenshot%202016-02-26%2016.30.06.png?dl=0))
This should keep the mailing address, but the wording should change to: 

"You received this email because of your generous gift to NewSpring Church."

Also, we need to remove the unsubscribe + update your profile links.

**Comment by jbaxleyiii** [comment]
@jonhorton this is great. Rock's current giving receipt (if you gave anywhere on Rock) doesn't include [Last 4 digits]. Because we are sending from Apollos, I can add that end but be aware it won't show up if giving from Rock

**Comment by jonhorton** [comment]
@jbaxleyiii That makes sense! Thanks!

On Fri, Feb 26, 2016 at 5:02 PM, James Baxley <notifications@github.com>
wrote:

> @jonhorton <https://github.com/jonhorton> this is great. Rock's current
> giving receipt (if you gave anywhere on Rock) doesn't include [Last 4
> digits]. Because we are sending from Apollos, I can add that end but be
> aware it won't show up if giving from Rock
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NewSpring/Apollos/issues/192#issuecomment-189502343>.
>



-- 
Jon Horton
Central Web Director
NewSpring Church
www.newspring.cc
Office: 864.965.9518
Cell: 919.218.6655
