### ISSUE TITLE
Verify inActive schedule workflow

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#194]
Whoever does this, please take screenshots along the way so @samclaridge can verify it is a great experience. There are some technical limitations (for instance scheduling multiple gifts as once) that required a UI change.

To verify:
- create a schedule
- make it inactive with a PATCH in Rock
- login to your account

**Comment by jbaxleyiii** [comment]
### in active schedule
<img width="1196" alt="screenshot 2016-02-25 23 23 42" src="https://cloud.githubusercontent.com/assets/4967600/13343142/8475e914-dc17-11e5-93aa-4475b04691fb.png">

### signed out
<img width="364" alt="screenshot 2016-02-25 23 24 04" src="https://cloud.githubusercontent.com/assets/4967600/13343140/84746bf2-dc17-11e5-8a8c-cd2f62d1327c.png">

### after signin, notified with modal to recover
<img width="367" alt="screenshot 2016-02-25 23 25 47" src="https://cloud.githubusercontent.com/assets/4967600/13343141/847535f0-dc17-11e5-9819-68720f8a12b4.png">

### allow option to reminder later
<img width="367" alt="screenshot 2016-02-25 23 25 54" src="https://cloud.githubusercontent.com/assets/4967600/13343143/847620a0-dc17-11e5-9722-981920ffa2db.png">

### if you choose to remind you later
<img width="367" alt="screenshot 2016-02-25 23 26 09" src="https://cloud.githubusercontent.com/assets/4967600/13343145/8478ec54-dc17-11e5-95b5-723a6cff74e3.png">

### schedules to be recovered
<img width="366" alt="screenshot 2016-02-25 23 26 32" src="https://cloud.githubusercontent.com/assets/4967600/13343144/847776f8-dc17-11e5-898c-692562a0fe78.png">

### giving to recover schedule 
<img width="364" alt="screenshot 2016-02-25 23 26 58" src="https://cloud.githubusercontent.com/assets/4967600/13343146/847e8dd0-dc17-11e5-9867-b111e32d2dd5.png">

### gift recovered
<img width="367" alt="screenshot 2016-02-25 23 27 07" src="https://cloud.githubusercontent.com/assets/4967600/13343147/847f9bc6-dc17-11e5-8217-6bcf352dc943.png">

### schedule is active in Rock
<img width="1192" alt="screenshot 2016-02-25 23 27 58" src="https://cloud.githubusercontent.com/assets/4967600/13343148/848159de-dc17-11e5-9bd2-b0fd1e0e7092.png">


## Bugs with above process
- [ ] credit card icon does not render when using saved payment account
- [ ] the previous schedule was actually not touched in Rock, instead a new schedule was linked to the persons account

@samclaridge @jonhorton UI open for review

**Comment by jonhorton** [comment]
@jbaxleyiii When the schedule is transferred, do it simply activate the imported one OR does it create a new one?

**First Screen**
We need to change the wording on this to be more clear that the user is transferring a schedule, and not simply reactivating an older schedule. The reality is that these schedules are active and will continue to charge the user's account until they transfer it. And they don't have access to the old system.

Heading: Transfer Your Schedule
Body: Our records show that you have active giving schedules in our previous system. To access your schedule within our new system, simply review your schedule and re-enter your payment details. If you're not ready to do this, your schedule will continue in our previous system until you transfer it.

**Remind me Later Screen**

Body: We know life is busy! We would be happy to remind you about transferring your schedules at a later date. 

Please be aware that your existing schedule will continue to charge the account on file until you transfer it for editing in our new system.

**Recover Schedule (under My Gifts)**
Let's change the Recover to "Transfer".

**Review and Complete Your Gift Screen**

Heading: Review and Transfer Your Schedule
Button: Schedule Now using 1111

Also, it was a little confusing on this screen because it only shows the amount and not the schedule. We need to add a review of the schedule somehow. Either on this screen, or perhaps we can prefill the main schedule form? On second thought, I can see how just a review would be ideal, but there may a need for a user to edit the schedule. Thoughts?

**Success Screen**
For both recovered schedules AND new schedules, this screen makes it sound like my card was just charged, instead of scheduled to be charged.

Can we update the text:
Thank you for your scheduled gift of [$Amount] [frequency] starting on [next date of schedule] from account [Last 4]. We will email a receipt to [Email]

---

I'll add more once I'm able to go through the process through the site/app!

**Comment by jbaxleyiii** [comment]
@jonhorton it activates the schedule in Rock and creates a new one in NMI

>  On second thought, I can see how just a review would be ideal, but there may a need for a user to edit the schedule. Thoughts?

I can add schedule details to the confirm and success page, it won't be editable but will work for recovering and creating schedules.

Thanks for the feedback!
