### ISSUE TITLE
Profile Image Is Not Horizontally Centered

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#302]
## Acceptance Criteria

- [ ] Profile image should be centered horizontally.

## Context

Viewing the profile page, the profile image does not appear to be quite horizontally centered like the name and city.

## UI Screenshot or Wireframe (optional)

![img_0579](https://user-images.githubusercontent.com/2465823/35997501-ad6553a2-0ce7-11e8-8f8a-967d9504936d.PNG)

**Comment by conrad-vanl** [comment]
Thanks @briankalwat !

I believe this is fixed in the latest expo build. You might make sure you're on the newest build by going here - https://expo.io/@newspring-builds/newspring-master 

and either with the expo app opened: shake your device, tap "Scan QR Code" and scan the code on that website,

or opening that link up on your mobile device then tapping the "Open in expo" button.

**Comment by conrad-vanl** [comment]
Closing as appears to be correct in latest build.

**Comment by conrad-vanl** [comment]
Feel free to re-open if issue persists.
