### ISSUE TITLE
Music should stop when playing video

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#311]
## Acceptance Criteria

- [ ] If I am playing music then navigate somewhere that has video it does not stop the music when I press play on the video

**Comment by burkeshartsis** [comment]
This is sort of trickier than I originally thought if we want to maintain a reasonable user experience. I see two paths forward, neither are particularly quick.

### Option 1
Because current videos are played in a web view we would need to integrate with the Wistia API so we can intercept taps/player state in the web view and pass them back to RN. This is gross and I don't really like it.

### Option 2
We add video playback to the current media player so that media state is all in one place. This would likely create a more robust media playback experience and open up the possibility for new features/capabilities down the road.

Down side, both of these require significant engineering effort. @conrad-vanl @IsaacHardy thoughts?

**Comment by burkeshartsis** [comment]
Ok I came up with a third option, that I would call a workaround but might work.

### Option 3
Currently we load the webviews inline. One thing we could do to boost initial load time would be to load a thumbnail (in RN land) with a play button. When the user taps the thumbnail we then load the webview, full screen the video player, and in an ideal world auto play it. Because the initial tap is happening in RN we can easily adjust app state accordingly (pause audio playback).

#### Pros
- Probably the fastest and easiest solution to implement.
- As mentioned this also gives the app view that's being rendered a perceived speed boost because the user isn't left waiting for a webview to load a media player they may never interact with.
- We can exert more control over the webviews initial loading experience.

**Comment by burkeshartsis** [comment]
I was hoping I would be able to do option 3 easily. That was predicated on the ability to tap a RN component that loads the webview with a the embed url set to autoplay. Problem is, [autoplay will basically never work](https://wistia.com/support/developers/embed-options#autoplay) on a mobile device.

My new favorite option is to use the native player! This would allow a option 3 like solution. @conrad-vanl what would it take to get #334 merged?

**Comment by conrad-vanl** [comment]
I don't like any of the options presented above other then migration to native player. Native player isn't a suitable option for the release timeline. So, my vote is to do nothing for now and not consider this a release blocking issue. User listening to audio and starting a video while listening to audio is an edge case, and they have the ability to easily pause the other if so, so mild inconvenience....and likely no affect on conversion rates or any sort of KPI.

Best long term solution IMO is to combine the audio and video players into a unified player (similar to how Spotify works)...pressing play on a video adds the video to your media queue, the video controls show up at the bottom of the screen like the audio controls, etc. A++ experience.
