### ISSUE TITLE
WEB: Sections nav styling

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#336]
## Acceptance Criteria

- [x] Section menu should display as is custom on the web version of Apollos when redirecting from an external site.
- [x] Section menu should display correctly when refreshing the page when viewing the sections nav.

## Context

If you click a section item that takes you to an external site, if you press the "back" button to come back to the app, the section menu will display as if the environment is native and covers the entire screen.

## UI Screenshot or Wireframe (optional)

![2018-02-14 09 43 33](https://user-images.githubusercontent.com/10745699/36210126-a1814fea-116b-11e8-82c8-ee07f2da0dbe.gif)

**Comment by richarddubay** [comment]
What if we just opened the links in another tab on the web? Is that a possibility? @burkeshartsis @IsaacHardy

**Comment by burkeshartsis** [comment]
Ok @richarddubay, I needed to look into this a little bit to make sure I pointed you in at the right thing. There ma So the root of you problem starts [here](https://github.com/NewSpring/Apollos/blob/sermon-audio/src/AppRouter.js#L84). There are actually three routes that are "broken" if navigate to these pages directly (or navigate away and come back directly). The styles that make them appear correctly when you navigate from within the app to them are [here](https://github.com/NewSpring/Apollos/blob/sermon-audio/src/%40ui/ModalView/ModalContainer.js#L25). This because the width for these views is defined by the modal itself. However, if you navigate to these views directly it doesn't use a modal view at all. 

As @conrad-vanl points out above you have some options. I would recommend probably go with his second option to always render these sections in a modal and then figure out how to fix the double nav bar problem show below.

<img width="1680" alt="boom" src="https://user-images.githubusercontent.com/2053547/36853158-b2324ff2-1d3b-11e8-9865-c7ce1c068d6d.png">

Another option if the the nav and bg problems seem bigger seem bigger than the original problem would be to add some media queries like you see on the [home feed](https://github.com/NewSpring/Apollos/blob/sermon-audio/src/tabs/Feed.js#L44) to account for when you navigate to these views directly. Hopefully that's enough information to get you some momentum in the right directions.

**Comment by richarddubay** [comment]
@burkeshartsis @IsaacHardy So one thing I'm seeing as I'm looking through this is that on our current site we don't update the route when the sections modal (or any modal) displays. So if you navigate away and then come back, the original page loads minus the modal. Is that something that was discussed at any point and determined impossible to do? Is that a limitation inside RN/RNW? Seems to me that coming back to the original page (and not the sections menu - or whatever modal) would be a better experience. Maybe it's too late to think through what that routing would look like but I just thought I'd bring it up.

**Comment by burkeshartsis** [comment]
@richarddubay If I'm honest that's really a question for @conrad-vanl.

**Comment by conrad-vanl** [comment]
We took a mobile first approach to this. From a mobile perspective, the sections screen is a full route, with the ability to go back to it, etc. so it makes sense to treat this view as a full route on mobile. The question then becomes how to support this on web. 

Right now we are treating all modals the same - making them routable because on mobile that allows us to make all these transitions consistent. 

In relation to react router, if you look at their website for advice on how to handle modals, their recommendation is similar to what we are doing. 

With that said, on web the sections menu isn’t really a modal, it’s a drop down menu. But then the question becomes do we really want to split code to improve this edge case experience on web...I’m not so sure that’s a good idea.

**Comment by richarddubay** [comment]
@conrad-vanl I get what you're saying. Sort of. You're probably doing things the right way. I have no experience to suggest otherwise. I apologize if that was implied in what I asked. All I have to go on is what our prior experience was like. 

I also don't have data to suggest it's NOT an edge case, but I'd guess that more than a few people are going to experience this. Maybe it's not something we need to worry about for the initial launch (outside of making the experience as good as we can), but If I was on the home feed and clicked the section menu, read the "About Us" page (or whatever page, you pick) and then came back to the screen below (or something like it) I would think something was broken. "What happened to the content on the page I was just on?", is something I think I'd ask. Anyway, I will defer to @IsaacHardy on what is important or not. 

![screenshot 2018-03-01 14 02 32](https://user-images.githubusercontent.com/3229463/36864095-a8145678-1d59-11e8-8038-e77b45246e87.png)

**Comment by burkeshartsis** [comment]
So my second option mentioned in my comment above could address this situation by removing the modal entirely in this instance and styling these views to look more like the home page. That is they would come back to the menu overplayed on maybe the video that plays on the home page or something. Just something prettier. I'm not sure it's a huge win at the moment but agree that the UX could be improved here.

**Comment by richarddubay** [comment]
I got you. I don't want to slow us down from launching by any means. I just have no idea about what was discussed or why things are the way they are. So...all the questions. ❤️ you all.

**Comment by conrad-vanl** [comment]
My other suggestion was going to be to allow the sections menu to be like it is now on master, but for the full screen view to put an image or something to the right do it looks more like a “page”. 

I agree that the experience isn’t optimum on web, but i do believe ts improved on mobile. 😐

**Comment by richarddubay** [comment]
@conrad-vanl @burkeshartsis @IsaacHardy If the idea is that coming back to the sections menu is the best option, then I think I agree that we should probably look at making this into a full-page experience at some point on web. I've got it displaying in the modal (like above) and am working on figuring out the menu doubling thing. Never having dealt with react-native stylesheets, I'm just trying to figure out how to make this happen. Maybe something with absoluteFillObject, potentially? Anyway, I think this will suffice for now. 

Guys...thanks so much for dealing with me and answering all my questions. Again, I apologize if I came off sounding like you all did anything wrong. Definitely not my intention.

**Comment by burkeshartsis** [comment]
@richarddubay no need to apologize for anything. All is perfectly well. It sounds like given the direction we want to head with this we can ditch the modal view and just add some media query styling to the views like we do on the home page. See [here](https://github.com/NewSpring/Apollos/blob/sermon-audio/src/tabs/Feed.js#L44)
