### ISSUE TITLE
Giving View HELP Link

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#392]
## Acceptance Criteria

- [ ] There should be a link on the giving view.

## Context

We need to implement a simple help link so our members can view helpful information if they have trouble giving.

**Comment by IsaacHardy** [comment]
@burkeshartsis We are trying to determine a good place for this link. Do you have any suggestions?

**Comment by burkeshartsis** [comment]
Two ideas come to mind that fit loosely into the paradigms we already have established. The first, you could put a note at the bottom of the give now page ala  the discover tab
![image](https://user-images.githubusercontent.com/2053547/37261832-a91f5a58-2575-11e8-93c5-4cec1cf7e5d6.png)

**Comment by burkeshartsis** [comment]
The second, you could add a help icon (something like a question mark in a circle of sorts) to the header ala the profile settings page. If you had a lot of information you wanted to display we could build an entire view for it. If you wanted to link to a Rock flow that might work too. Down side to his is that it's very present. Which both good an bad but is to say you might get people clicking it more often than they really need to just because they want some handholding. People in need of real problem solving are often more motivated to look for help so it's less necessary to put it front and center. In short, just depends on how you plan to help.

![image](https://user-images.githubusercontent.com/2053547/37261887-f1781e7a-2575-11e8-945c-79b4dd27d8a5.png)

**Comment by IsaacHardy** [comment]
@burkeshartsis I like that first idea. I know Michael is adamant about keeping this link somewhere on the Give Now page so that solution seems best. I'm going to go investigate that component to see how I can implement it into the Give now area. Thanks!
