### ISSUE TITLE
Address state field inconsistent and defaulting to SC

### ISSUE THREAD

**Issue by burkeshartsis** [NewSpring/Apollos#440]
## Acceptance Criteria

- [x] The address state field should save the same type in all forms!
- [x] The address state field should have the same UI (dropdown) in all forms.
- [ ] The address state field (dropdown) should only display values relative to your country.

## Context

If the user has an address (state) defined in their user profile and try to give with a new payment method the state dropdown doesn't auto-populate with the correct state (always defaults to SC).
Additionally, these two forms (`BillingAddressForm` and `ProfileAddressForm`) save different data types for state. `BillingAddressForm` saves a `stateId` (number sometimes in the form of a string) and `ProfileAddressForm` saves `values.state` (state name in the form of a string). Lastly, the values shown in the state dropdown do not currently represent the country that is selected.

#### Billing Address Form
![simulator screen shot - iphone x - 2018-03-29 at 09 18 49](https://user-images.githubusercontent.com/2053547/38099297-3e2af3ca-3348-11e8-8356-07c2f512db55.png)
#### Profile Address Form
![simulator screen shot - iphone x - 2018-03-29 at 09 18 07](https://user-images.githubusercontent.com/2053547/38099312-4a9ada3a-3348-11e8-9d18-04490664da19.png)
#### Preferred UI for State selection
![simulator screen shot - iphone x - 2018-03-29 at 11 50 06](https://user-images.githubusercontent.com/2053547/38099339-5a833a0a-3348-11e8-8293-b53413262a15.png)

**Comment by conrad-vanl** [comment]
IRC, this is only an issue if someone goes to their profile form in the app and types out their full state instead of abbreviating it - like if I type "Texas" in my profile instead of "TX" and save.

FWIW, in the current app, I couldn't get the profile form to save to my profile at all 🤔 

Anyways, the easy fix here is to just use a dropdown menu in the profile form. That will cause us to save the abbreviated state name which will fix the checkout form referenced at the beginning of the issue. (I believe)

**Comment by richarddubay** [comment]
@burkeshartsis @IsaacHardy I think the idea right now is to move that last bullet point into a different issue so that this issue can get moving.
