### ISSUE TITLE
Decrease the size of the "Give as a Guest" button

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#473]
## Acceptance Criteria

- [ ] The "Give as a Guest" button should be smaller.

**Comment by cdanwards** [comment]
@IsaacHardy with us making this button smaller, I'm going to have to use a `Chip` instead of a `Button` in order to change its height. The thought then becomes what is the design supposed to look like on web? The form is currently constructed in a way so that the buttons are in a row. Changing the size of this makes that row not as aesthetically pleasing.
