### ISSUE TITLE
System won't keep me signed in

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#491]
I've been experiencing this more frequently—the system doesn't keep me signed in.

As I'm typing this, I realized that part of the problem may be that I'm signed out on my desktop whenever I sign in on my phone. (This is super annoying).

After this happens, when I go back to the desktop, it acts like I'm signed in
- after a few seconds, register button disappears
- Give as guest stays
- Sign In becomes 'Sign In with (card image)' but no last 4

A refresh shows me that I am, in fact, signed out.

**Comment by johnthepink** [comment]
@jonhorton yep. we are tracking on #273. We think it has to do with with some of the settings that are updated on the user from Rock when signing in.

**Comment by jbaxleyiii** [comment]
@johnthepink @jonhorton if I had to bet, its because of this:

https://github.com/NewSpring/Apollos/blob/master/core/methods/accounts/server/login.js#L82

and corresponding docs

http://docs.meteor.com/#/full/accounts_setpassword

Should be a pretty easy thing to test (open chrome and safari with the change locally, verify it still signs you out, then change to `Accounts.setPassword(userAccount._id, password, { logout: false })` and try again

**Comment by jbaxleyiii** [comment]
confirmed that fixed it:

<img width="1678" alt="screenshot 2016-04-10 19 07 13" src="https://cloud.githubusercontent.com/assets/4967600/14413684/80c7f130-ff4f-11e5-9361-b59e478c654d.png">
