### ISSUE TITLE
[Web] App becomes unresponsive after canceling a scheduled giving transaction

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#604]
Steps to reproduce:

1. Schedule a giving amount to complete for the following day.
2. Head to dashboard and cancel scheduled giving transaction
3. Press the back button
3. The App will then become unresponsive

There are no console errors nor sentry errors for this issue.

**Comment by conrad-vanl** [comment]
I'm having difficulties reproducing on latest alpha. Can you perhaps record your interaction? or give more detail to reproduce?

**Comment by richarddubay** [comment]
***Steps To Reproduce***
---
On beta.apollos.newspring.cc:
Go to give now
Enter an amount to give.
Schedule that amount for tomorrow.
Finish the give process so that the schedule is active and shows on your dashboard.
View the schedule details
Click to cancel the schedule.
Click either the built-in back button or the browser back button.
The screen will be frozen.
