### ISSUE TITLE
Inline image within wygwam don't appear within an entry in the app

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#615]
**Steps to reproduce**
- View the latest story called Life after death
- scroll down until you see an outlined box of where an image should be.
- (View this article on desktop to see what images should exist)

**Buggy Behavior**
- Images inside the body field don't display within the app
- This could affect stories, articles or devos

Expected Behavior
- Images load
- If possible, images should be cropped / loaded from the cloudfront cdn instead of S3 Origin (in EE, this is handled through CE Cache)

**Comment by johnthepink** [comment]
Looks like we need to better check for EE tags:

```html
<img alt="" src="{assets_38042://s3.amazonaws.com/ns.images/newspring/editorial/content/PhillipAmyMyers_compressed.jpg}" style="float:left">
```

**Comment by johnthepink** [comment]
fixed by https://github.com/NewSpring/Heighliner/pull/64

I'm going to open a separate issue for converting s3 urls to cloudfront for inline content, because we need to do that everywhere.

<img width="578" alt="screenshot 2016-06-14 19 39 56" src="https://cloud.githubusercontent.com/assets/816517/16063521/d12cf602-3267-11e6-8cd4-5a401b68234f.png">
