### ISSUE TITLE
Convert S3 urls to Cloudfront

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#647]
per https://github.com/NewSpring/Apollos/issues/615, when EE sends us markup, we need to convert the s3 url to a cloudfront url.

**Comment by johnthepink** [comment]
@jonhorton fixed by https://github.com/NewSpring/Heighliner/pull/65

**Comment by johnthepink** [comment]
<img width="481" alt="screenshot 2016-06-14 20 14 13" src="https://cloud.githubusercontent.com/assets/816517/16064136/9a5d0acc-326c-11e6-8558-f4b824e271af.png">

**Comment by jbaxleyiii** [comment]
@johnthepink I wonder if we should create a `url` field on the `images` type. Then heighliner could prioritize the fastest url. I don't know if all images will have a `cloudfront` if the pages have been rendered yet. So this fix may not prove robust enough

**Comment by jbaxleyiii** [comment]
I can handle that in the new heighlier build fwiw

**Comment by johnthepink** [comment]
@jbaxleyiii yea that would be cool. The issue with these was that the image is buried in the markup and is displayed between content. So we'd need to do some trickery.

Is EE controlling whether the S3 images are public or not then? I could be wrong, but if cloudfront is just a mask to the S3 bucket, then unless it's set to private it should resolve.

**Comment by jbaxleyiii** [comment]
@johnthepink I'm not 100% sure tbh. Need to investigate

**Comment by johnthepink** [comment]
@jbaxleyiii cool. i'll reopen this so we remember to check it out.

**Comment by jonhorton** [comment]
@jbaxleyiii @johnthepink  On EE, we use [this trickery](https://github.com/NewSpring/NewSpring/blob/master/assets/_source/templates/global/_layouts.group/editorial-entry.html#L30-L34) to convert an S3 url to cloudfront. This is almost exclusively used with the contents of a wygwam field. Because the source files are uploaded through the assets module in EE, they're always set to public. CE Image also ensures modified images are set to public.

What happens is the CE Image bulk tag will go through any <img> tag within it, find the image, filter it according to the parameters (usually a crop/resize), upload the modified file to a specific folder, using the same file structure, and return a cloudfront url to that modified image. (Source image is left untouched.) The returned path is cached so when the wygwam field is parsed again, it returns the cloudfront url.

The settings for the CE Image plugin, including the altered folders and cloudfront url are specified in our [EE config](https://github.com/NewSpring/NewSpring/blob/master/config/config.master.php#L338-L346).

**Comment by johnthepink** [comment]
@jonhorton awesome thanks! So, if they are always public, we won't have to worry about s3 images not existing at the cloudfront version of the url. We should be good on that front.

I did notice the cropping. The url we get from the EE markup is the full size original image (2224 x 2264 in the image above). It'd be nice to not load images that big in the app, since it's displaying at like 1/10 the size. I'd say we probably don't want to duplicate the cropping on heighliner. We should find out how to map the CE image mysql table, though, so we can have access to all versions of the image it creates.

**Comment by johnthepink** [comment]
We confirmed that cloudfront versions of the urls we are using will always exists so I'll close this. We have a separate issue for getting compressed images.
