### ISSUE TITLE
Compressed Images

### ISSUE THREAD

**Issue by delianides** [NewSpring/Apollos#676]
the image size loading from EE is way to large for any mobile device. We need to utilize EE's ability to resize images and load them to cloudfront.

**Comment by johnthepink** [comment]
I've had a few conversations with @jbaxleyiii about this. It is not possible to pull the images directly from CE Image in EE, because it does not store them in the database anywhere. It creates the images needed dynamically at the template level, and uploads them to S3. We could get in to the business of listing and searching S3 over the API, but that feels dirty to me. So, I think we should handle image processing some other way.

### Image Processor

Initially, we were thinking we may do the image processing inside of Heighliner. But, this would be CPU intensive, and wouldn't actually happen that often. I think it would be really cool to use AWS Lambda to do the image processing. That will be really cheap to do, and it will provide a good separation of concern from Heighliner.

### Triggering Image Processing

There are a couple different ways we can trigger the image processing.

1. On expression engine upload
2. On image added to S3 bucket
3. When Heighliner only receives one image from a data store

I like the idea of Heighliner triggering the image processing. Then, we wouldn't need to back process our entire database of images at one time. Heighliner would just ask for images and when it receives only 1, it can return the 1 image it has to the app, and send it to Lambda for processing. Then, when that image is requested again, it will have multiple versions of the image to choose from.

**Comment by johnthepink** [comment]
This was handled using a Lambda function that gets triggered each time an image gets added to an S3 bucket. Then, we batch processed all existing images by triggering Lambda functions for each of them.

Relevant code is here:

https://github.com/NewSpring/images-lambda
https://github.com/NewSpring/batcher
