### ISSUE TITLE
Can't give through the app

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#727]
**Steps to Reproduce**
* Visit the give section of the app
* Have a saved payment account
* Tap "Review Using ###"

**Buggy Behavior**
* Nothing happens, and the users is never advanced through the next step of the give process.

**Comment by johnthepink** [comment]
## tl;dr 

This was due to an issue with our app build process, and should be fixed now.

## details

During development, I generally have the shared `apollos` code folder symlinked in to my `node_modules` directory. Doing this causes issues with shared dependencies between our shared code and our app code. Specifically, our `Promise` functionality wasn't getting included.
