### ISSUE TITLE
Music from sermons

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#831]
I've noticed that our existing apps (iOS, AppleTV, and I assume Roku as well) use a version of the sermon that does not contain the music. However, the website does show the music. So, I have a few questions:

1. Are we allowed to display the music in app?
2. Should we display music in app?

cc @jonhorton @jbaxleyiii

**Comment by jonhorton** [comment]
Hey @johnthepink, this is a great question!

Here's what I know:
- For most music that we didn't write, we're only licensed to stream it—not make it available for download.
- Because of this, we have typically made the version with music available from Ooyala only, while the mp3/mp4 versions of content (available for download via site or podcast) exclude music.

I think it could work to take the same stance within the app.
- Watching a sermon can include music, while downloading it uses the existing mp3/mp4 files. 
- This would also work with the existing process that production has.

Would there be anything preventing that? Thoughts?

**Comment by johnthepink** [comment]
@jonhorton Thanks! So, if I'm understanding correctly, the way we have it currently implemented is fine? And then when/if we add the ability to store sermons locally, we would need to use the non-music version? We will need to add the ability to pull both versions from Heighliner at that point.

**Comment by jonhorton** [comment]
@johnthepink Yep, current implementation should work! And you're correct, we'd need to use the non-music version for local storage.

For that, we do have the mp4/mp3 version attached to the sermon entry. On the site they show up under the [Downloads section](https://www.dropbox.com/s/sr6whruvxbrgpqp/Screenshot%202016-07-27%2009.49.39.png?dl=0), and in the DB, I believe they're a matrix field.

Let me know if you need anything else related to this!

**Comment by johnthepink** [comment]
@jonhorton Perfect. Thanks for the info. I'm closing this for now as those features will be separate issues in the future. Just wanted to make sure we didn't need to make the switch now.
